name: ci

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout the code
        uses: actions/checkout@v3

      - name: fetch dependencies
        run: go mod download

      - name: run test race with coverage
        run: make coverage-badge

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true
